// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6V7g7PP33E9GMsV5mwxMZbZi2rnSSSL8',
    appId: '1:66678746770:web:b081683330e1116b89c04b',
    messagingSenderId: '66678746770',
    projectId: 'ai-expense-tracker-99205',
    authDomain: 'ai-expense-tracker-99205.firebaseapp.com',
    storageBucket: 'ai-expense-tracker-99205.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhy_T04B25mVKNjd_zhmoCcAXzntftwbM',
    appId: '1:66678746770:android:46783e982ca7c93989c04b',
    messagingSenderId: '66678746770',
    projectId: 'ai-expense-tracker-99205',
    storageBucket: 'ai-expense-tracker-99205.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWe0yxQuusMccF3TyMCwW9op0l36iepjc',
    appId: '1:66678746770:ios:f0549c83b408aaf989c04b',
    messagingSenderId: '66678746770',
    projectId: 'ai-expense-tracker-99205',
    storageBucket: 'ai-expense-tracker-99205.firebasestorage.app',
    iosBundleId: 'com.example.aiExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWe0yxQuusMccF3TyMCwW9op0l36iepjc',
    appId: '1:66678746770:ios:f0549c83b408aaf989c04b',
    messagingSenderId: '66678746770',
    projectId: 'ai-expense-tracker-99205',
    storageBucket: 'ai-expense-tracker-99205.firebasestorage.app',
    iosBundleId: 'com.example.aiExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6V7g7PP33E9GMsV5mwxMZbZi2rnSSSL8',
    appId: '1:66678746770:web:34a7c69be75c6a3d89c04b',
    messagingSenderId: '66678746770',
    projectId: 'ai-expense-tracker-99205',
    authDomain: 'ai-expense-tracker-99205.firebaseapp.com',
    storageBucket: 'ai-expense-tracker-99205.firebasestorage.app',
  );

}